load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_test(
    name = "leetcode",
    srcs = ["leetcode_test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "atoi_test",
    srcs = ["atoi_test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "test",
    srcs = ["test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "test2",
    srcs = ["test2.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "max_freq_stack",
    srcs = ["maxFreqStack.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "monotonic_queue",
    srcs = ["monotonicQueue.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "twitter",
    srcs = ["twitter.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "myqueue",
    srcs = ["myqueue.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "priority_queue",
    srcs = ["myPriorityQueue.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
cc_test(
    name = "interval",
    srcs = ["interval_schedule.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
