load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_test(
    name = "carray_test",
    srcs = ["c-array_test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "reference_test",
    srcs = ["reference_test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
