load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "string_test",
    srcs = ["string_test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "detail_test",
    srcs = ["detail_test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)