load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "stream_test",
    srcs = ["stream_test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "state_test",
    srcs = ["state_test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "stdio_function_test",
    srcs = ["stdio_function_test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "manipulator_test",
    srcs = ["manipulator_test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "file_access_test",
    srcs = ["file_access_test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "file_flag_test",
    srcs = ["file_flag_test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "format_test",
    srcs = ["format_test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "string_stream_test",
    srcs = ["string_stream_test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "user_define_io_test",
    srcs = ["user_define_io_test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)