load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "set_test",
    srcs = ["set_test.cc"],
    deps = [
        "//Stl/Container:common",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "map_test",
    srcs = ["map_test.cc"],
    deps = [
        "//Stl/Container:common",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
