load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "type_trait_test",
    srcs = ["type_trait_test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "reference_wrapper_test",
    srcs = ["reference_wrapper_test.cc"],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
