load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "op_test",
    srcs = ["operation_test.cc"],
    deps = [
        "//Stl/Container:common",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
