load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_test(
    name = "async_test",
    srcs = [
        "async_test.cc",
    ],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "thread_test",
    srcs = [
        "thread_test.cc",
    ],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "promise_test",
    srcs = [
        "promise_test.cc",
    ],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "packaged_task_test",
    srcs = [
        "packaged_task_test.cc",
    ],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "mutex_lock_test",
    srcs = [
        "mutex_lock_test.cc",
    ],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "condition_variable_test",
    srcs = [
        "condition_variable_test.cc",
    ],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "atomic_test",
    srcs = [
        "atomic_test.cc",
    ],
    deps = [
        "@gtest",
        "@gtest//:gtest_main",
    ],
)