load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_test(
    name = "array_test",
    srcs = ["array_test.cc"],
    deps = [
        "//Stl/Container:common",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "vector_test",
    srcs = ["vector_test.cc"],
    deps = [
        "//Stl/Container:common",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "deque_test",
    srcs = ["deque_test.cc"],
    deps = [
        "//Stl/Container:common",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "list_test",
    srcs = ["list_test.cc"],
    deps = [
        "//Stl/Container:common",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "fl_test",
    srcs = ["forward_list_test.cc"],
    deps = [
        "//Stl/Container:common",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
